import React from 'react';
import { format } from 'date-fns';
import { ShieldAlert, FileText, Calendar } from 'lucide-react';

import Logo from '../ui/Logo';
import { pdfLogoLocalPath } from '../ui/logoData';

interface AuditLog {
    id: string;
    action: string;
    performed_by: string;
    target_user_id: string;
    details: any;
    created_at: string;
    performer_name?: string;
    target_name?: string;
}

interface AttendanceAuditReportProps {
    logs: AuditLog[];
    generatedBy?: string;
}

const AttendanceAuditReport: React.FC<AttendanceAuditReportProps> = ({ logs, generatedBy }) => {
    
    if (logs.length === 0) {
        return (
            <div className="flex flex-col items-center justify-center p-12 text-gray-500 bg-gray-50 rounded-xl border border-dashed border-gray-300">
                <ShieldAlert className="w-10 h-10 mb-3 text-gray-400" />
                <p>No audit logs found.</p>
            </div>
        );
    }

    return (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden p-8">
            <div className="flex justify-between items-center border-b pb-4 mb-6">
                <Logo className="h-10" localPath={pdfLogoLocalPath} />
                <div className="text-right">
                    <h1 className="text-xl font-bold">Audit Log Report</h1>
                     <p className="text-xs text-gray-500 mt-1">Generated: {format(new Date(), 'dd MMM yyyy HH:mm')}</p>
                    {generatedBy && <p className="text-xs text-gray-500">Generated by: {generatedBy}</p>}
                </div>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                    <thead className="text-xs text-gray-700 uppercase bg-gray-50 border-b">
                        <tr>
                            <th className="px-6 py-3">Date & Time</th>
                            <th className="px-6 py-3">Action</th>
                            <th className="px-6 py-3">Performed By</th>
                            <th className="px-6 py-3">Target Employee</th>
                            <th className="px-6 py-3">Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        {logs.map((log) => (
                            <tr key={log.id} className="bg-white border-b hover:bg-gray-50">
                                <td className="px-6 py-4 whitespace-nowrap text-gray-500">
                                    {format(new Date(log.created_at), 'dd MMM yyyy, HH:mm')}
                                </td>
                                <td className="px-6 py-4 font-medium text-gray-900">
                                    <span className="px-2 py-1 bg-blue-50 text-blue-700 rounded-md text-xs border border-blue-100">
                                        {log.action}
                                    </span>
                                </td>
                                <td className="px-6 py-4 font-medium text-gray-900">
                                    <div className="flex items-center">
                                        <div className="w-6 h-6 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-700 mr-2 text-xs">
                                            {log.performer_name?.charAt(0)}
                                        </div>
                                        {log.performer_name}
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-gray-900">
                                    <div className="flex items-center">
                                        <div className="w-6 h-6 rounded-full bg-emerald-100 flex items-center justify-center text-emerald-700 mr-2 text-xs">
                                            {log.target_name?.charAt(0)}
                                        </div>
                                        {log.target_name}
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-gray-600 max-w-xs truncate">
                                    <div className="flex flex-col gap-1">
                                        {log.details.date && (
                                            <span className="flex items-center text-xs">
                                                <Calendar className="w-3 h-3 mr-1" /> {log.details.date}
                                            </span>
                                        )}
                                        {log.details.reason && (
                                            <span className="flex items-center text-xs italic text-gray-500" title={log.details.reason}>
                                                <FileText className="w-3 h-3 mr-1" /> {log.details.reason}
                                            </span>
                                        )}
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default AttendanceAuditReport;
