import os
import re

base_path = r"e:\onboarding all files\Paradigm Office 2\supabase"
migrations_dir = os.path.join(base_path, "migrations")
output_file = r"e:\onboarding all files\Paradigm Office 2\full_backup_consolidated.sql"

def get_sql_files():
    files = []
    # 1. Base Schema
    schema_file = os.path.join(base_path, "schema.sql")
    if os.path.exists(schema_file):
        files.append(schema_file)
    
    # 2. Migrations (sorted alphabetically/chronologically)
    if os.path.exists(migrations_dir):
        mig_files = [f for f in os.listdir(migrations_dir) if f.endswith(".sql")]
        mig_files.sort()
        for f in mig_files:
            files.append(os.path.join(migrations_dir, f))
            
    # 3. Other RPC scripts if any
    rpc_file = os.path.join(base_path, "rpc_approve_user.sql")
    if os.path.exists(rpc_file):
        files.append(rpc_file)
        
    return files

def consolidate():
    sql_files = get_sql_files()
    with open(output_file, "w", encoding="utf-8") as outfile:
        outfile.write("-- =============================================\n")
        outfile.write("-- FULL DATABASE BACKUP (CONSOLIDATED)\n")
        outfile.write("-- Generated by Antigravity AI\n")
        outfile.write(f"-- Date: {os.popen('date /t').read().strip()}\n")
        outfile.write("-- =============================================\n\n")
        
        for filepath in sql_files:
            filename = os.path.basename(filepath)
            outfile.write(f"\n-- ---------------------------------------------\n")
            outfile.write(f"-- Source: {filename}\n")
            outfile.write(f"-- ---------------------------------------------\n\n")
            
            content = ""
            try:
                with open(filepath, "r", encoding="utf-8") as infile:
                    content = infile.read()
            except UnicodeDecodeError:
                with open(filepath, "r", encoding="latin-1") as infile:
                    content = infile.read()
            
            outfile.write(content)
            outfile.write("\n")
                
    print(f"Consolidated backup created: {output_file}")

if __name__ == "__main__":
    consolidate()
