-- Insert dummy costing data for testing
-- Uses the first organization as the site. Change the site_id subquery if needed.

INSERT INTO site_costing_master (id, site_id, status, version_no, config_data, created_at, updated_at)
VALUES (
  gen_random_uuid()::text,
  (SELECT id FROM organizations LIMIT 1),  -- ← Change this to a specific site_id if needed
  'Draft',
  1,
  '{
    "effective_from": "2026-03-20",
    "effective_to": "2027-03-19",
    "billing_cycle": "Monthly",
    "admin_charge_percent": 10,
    "resources": [
      {
        "id": "res_001",
        "department": "Administrative",
        "designation": "Facility Manager",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 56000,
        "billing_model": "Per Month",
        "total": 56000,
        "working_hours_start": "09:00",
        "working_hours_end": "18:00",
        "shift_type": "General",
        "shifts": [{"name": "General", "start_time": "09:00", "end_time": "18:00"}],
        "open_shift_allowed": false,
        "weekly_off_applicable": true,
        "weekly_off_type": "Sunday",
        "leave_applicable": true,
        "earned_leave_count": 38,
        "sick_leave_count": null,
        "holiday_billing_rule": "Billable if Availed Holiday, if worked on Holiday the additional duty to be carry forwarded (Compensate in coming month by availing leave)",
        "holiday_payment_rule": "Payable if availed Holiday, if worked on Holiday the additional duty to be carry forwarded (Compensate in coming month by availing leave)",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "During PNF, based on no of months be worked min+only the deductions will be done",
        "employment_verification": true,
        "background_verification": true,
        "police_verification": true
      },
      {
        "id": "res_002",
        "department": "Housekeeping",
        "designation": "Housekeeper/Janitor Heavy Works (Male)",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 16418,
        "billing_model": "Per Month",
        "total": 16418,
        "working_hours_start": "08:30",
        "working_hours_end": "17:30",
        "shift_type": "General",
        "shifts": [],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "holiday_payment_rule": "Work for 2-3 hrs max 4 hrs, Pay 1 duty - if not worked 0 duty",
        "duty_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": true,
        "background_verification": false,
        "police_verification": true
      },
      {
        "id": "res_003",
        "department": "Housekeeping",
        "designation": "Housekeeper/Janitor (Female)",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 6,
        "billing_rate": 16418,
        "billing_model": "Per Month",
        "total": 98508,
        "working_hours_start": "08:30",
        "working_hours_end": "17:30",
        "shift_type": "General",
        "shifts": [],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "holiday_payment_rule": "Work for 2-3 hrs max 4 hrs, Pay 1 duty - if not worked 0 duty",
        "duty_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "uniform_deduction": true,
        "uniform_deduction_note": "",
        "employment_verification": true,
        "background_verification": false,
        "police_verification": true
      },
      {
        "id": "res_004",
        "department": "Gardening",
        "designation": "Gardener",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 3,
        "billing_rate": 18708,
        "billing_model": "Per Month",
        "total": 56124,
        "working_hours_start": "08:30",
        "working_hours_end": "17:30",
        "shift_type": "General",
        "shifts": [],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "holiday_payment_rule": "Work for 2-3 hrs max 4 hrs, Pay 1 duty - if not worked 0 duty",
        "duty_rule": "Work for 2-3 hrs max 4 hrs, claim 1 duty - if not worked 0 duty",
        "uniform_deduction": true,
        "uniform_deduction_note": "",
        "employment_verification": true,
        "background_verification": false,
        "police_verification": true
      },
      {
        "id": "res_005",
        "department": "Plumbing",
        "designation": "Plumber Cum Pool Operator",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 29390,
        "billing_model": "Per Month",
        "total": 29390,
        "working_hours_start": "09:00",
        "working_hours_end": "18:00",
        "shift_type": "General",
        "shifts": [],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for full day and claim OT i.e, double duty - if not worked 1 holiday duty be claimed",
        "holiday_payment_rule": "Work for full day and Pay OT i.e, double duty - if not worked 1 holiday duty be paid",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": false,
        "background_verification": false,
        "police_verification": true
      },
      {
        "id": "res_006",
        "department": "Electrical",
        "designation": "Lead Electrician",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 24226,
        "billing_model": "Per Month",
        "total": 24226,
        "working_hours_start": "07:00",
        "working_hours_end": "14:00",
        "shift_type": "1st Shift",
        "shifts": [
          {"name": "1st Shift", "start_time": "07:00", "end_time": "14:00"},
          {"name": "2nd Shift", "start_time": "14:00", "end_time": "22:00"},
          {"name": "3rd Shift", "start_time": "22:00", "end_time": "07:00"}
        ],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for full day and claim OT i.e, double duty - if not worked 1 holiday duty be claimed",
        "holiday_payment_rule": "Work for full day and Pay OT i.e, double duty - if not worked 1 holiday duty be paid",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": false,
        "background_verification": true,
        "police_verification": true
      },
      {
        "id": "res_007",
        "department": "Electrical",
        "designation": "Lead Electrician",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 24226,
        "billing_model": "Per Month",
        "total": 24226,
        "working_hours_start": "14:00",
        "working_hours_end": "22:00",
        "shift_type": "2nd Shift",
        "shifts": [
          {"name": "1st Shift", "start_time": "07:00", "end_time": "14:00"},
          {"name": "2nd Shift", "start_time": "14:00", "end_time": "22:00"},
          {"name": "3rd Shift", "start_time": "22:00", "end_time": "07:00"}
        ],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for full day and claim OT i.e, double duty - if not worked 1 holiday duty be claimed",
        "holiday_payment_rule": "Work for full day and Pay OT i.e, double duty - if not worked 1 holiday duty be paid",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": false,
        "background_verification": true,
        "police_verification": true
      },
      {
        "id": "res_008",
        "department": "Electrical",
        "designation": "Multi Technician",
        "cost_centre": "",
        "unit_type": "Manpower",
        "quantity": 1,
        "billing_rate": 27324,
        "billing_model": "Per Month",
        "total": 27324,
        "working_hours_start": "22:00",
        "working_hours_end": "07:00",
        "shift_type": "3rd Shift",
        "shifts": [
          {"name": "1st Shift", "start_time": "07:00", "end_time": "14:00"},
          {"name": "2nd Shift", "start_time": "14:00", "end_time": "22:00"},
          {"name": "3rd Shift", "start_time": "22:00", "end_time": "07:00"}
        ],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "Work for full day and claim OT i.e, double duty - if not worked 1 holiday duty be claimed",
        "holiday_payment_rule": "Work for full day and Pay OT i.e, double duty - if not worked 1 holiday duty be paid",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": false,
        "background_verification": true,
        "police_verification": true
      },
      {
        "id": "res_009",
        "department": "Electrical",
        "designation": "Reliever Charges For MEP Staff",
        "cost_centre": "",
        "unit_type": "Lumpsum",
        "quantity": null,
        "billing_rate": 17528,
        "billing_model": "Lumpsum",
        "total": 17528,
        "working_hours_start": "",
        "working_hours_end": "",
        "shift_type": "General",
        "shifts": [],
        "open_shift_allowed": false,
        "weekly_off_applicable": false,
        "weekly_off_type": "",
        "leave_applicable": false,
        "earned_leave_count": null,
        "sick_leave_count": null,
        "holiday_billing_rule": "",
        "holiday_payment_rule": "",
        "duty_rule": "",
        "uniform_deduction": false,
        "uniform_deduction_note": "",
        "employment_verification": false,
        "background_verification": false,
        "police_verification": false
      }
    ],
    "additional_charges": [
      {
        "id": "chg_001",
        "charge_name": "Communication Charges",
        "charge_type": "Fixed",
        "amount": 1200,
        "frequency": "3"
      }
    ]
  }'::jsonb,
  now(),
  now()
);

-- Verify: Expected SUB TOTAL = 350,944 | Admin 10% = 35,094.4 | Grand Total = 386,038.4
SELECT id, site_id, status, 
  config_data->'admin_charge_percent' as admin_pct,
  jsonb_array_length(config_data->'resources') as resource_count
FROM site_costing_master 
ORDER BY created_at DESC 
LIMIT 1;
